added histogram
js-tasks-ru/htmlcss-20240216_chin-chin-23 pull request #5
Opened 2024-03-12 14:21 UTC by Chingiskhan1

2024-03-12 14:21 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-03-12 14:27 UTC, GSemikozov requested changes

2024-03-12 14:27 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    width: 354px;
лишнее

2024-03-12 14:27 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram-text {
отсюда и ниже - все классы переписать в соответствии с БЭМ

2024-03-12 14:27 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    margin-bottom: 40px;
39

2024-03-12 14:27 UTC, GSemikozov commented on 04-lection2/01-histogram/index.html
> +                <p class="orders-text orders-text__details"> View all </p>
`<a>`

2024-03-12 14:27 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.orders-text__details {
margin-top: 3px

2024-03-12 14:27 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    align-items: baseline;
flex-end

2024-03-12 14:27 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    width: 9px;
flex-basis

2024-03-13 13:37 UTC, Chingiskhan1 commented on 04-lection2/01-histogram/histogram.css
> +    width: 9px;
что это значит?

2024-03-13 13:38 UTC, Chingiskhan1 commented on 04-lection2/01-histogram/histogram.css
> +    width: 354px;
почему лишнее?
по дизайну же есть и ширина, падинги, и бордер

2024-03-14 11:50 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    width: 354px;
лишнее - ограничение ширины)

2024-03-14 11:50 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    width: 9px;
на занятии по флексбоксу изучали. Это базовая ширина

2024-03-14 14:29 UTC, GSemikozov requested changes
надо поправить конфликты

2024-03-14 14:29 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.chart__item--100 {
а почему модификаторы через `--` а не `_`?

2024-03-18 18:06 UTC, Chingiskhan1 commented on 04-lection2/01-histogram/histogram.css
> +.chart__item--100 {
Больше нравится Стиль Two Dashes.
Значение модификатора отделяется от его имени двумя дефисами (--).
или что-то не так понял?

2024-03-20 15:29 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.chart__item--100 {
просто мы такой способ не изучали, этого нет в оф доке и это называется "модифицированный БЭМ", так что видимо знание было почерпнуто из каких-то других источников :) но так тоже можно, только главное сохранять одинаковый подход во всем проекте

2024-03-22 19:34 UTC, GSemikozov approved these changes

2024-03-22 19:34 UTC, merged